#!/usr/bin/env python3
"""Discovers every AWS account in the Organization and generates one Ansible
dynamic-inventory file + one AWS CLI profile per account, so growing the
fleet by adding an AWS account requires zero manual Ansible configuration.

Run from the automation/hub account with credentials that can call
organizations:ListAccounts (a read-only, org-management-account-only API)
and sts:AssumeRole into AnsibleSpokeRole in every member account.

Usage:
    python3 generate_account_inventories.py \
        --hub-profile automation-hub \
        --region us-east-1

This writes:
  ~/.aws/config                        -- one [profile acct-<id>] block per account
  ansible/inventory/accounts/<id>.aws_ec2.yml  -- one dynamic inventory file per account

Re-run this on a schedule (or from CI before every playbook run) so newly
created/closed accounts are picked up automatically -- this is the concrete
answer to "how does the solution scale as more accounts are added".
"""
from __future__ import annotations

import argparse
import configparser
import os
from pathlib import Path

import boto3

SPOKE_ROLE_NAME = "AnsibleSpokeRole"
INVENTORY_TEMPLATE = """\
# Auto-generated by generate_account_inventories.py -- do not hand-edit.
# Regenerate by re-running that script; it is idempotent.
plugin: amazon.aws.aws_ec2
profile: {profile_name}
regions:
{region_lines}
filters:
  "tag:Monitoring": "disk"
  instance-state-name: running
keyed_groups:
  - key: tags.Environment
    prefix: env
  - key: placement.region
    prefix: region
compose:
  ansible_host: instance_id
  ansible_connection: "'community.aws.aws_ssm'"
  ansible_aws_ssm_region: placement.region
  ansible_aws_ssm_bucket_name: "'ansible-ssm-transfer-{account_id}-{primary_region}'"
  aws_account_id: "'{account_id}'"
  aws_account_name: "'{account_name}'"
cache: true
cache_plugin: jsonfile
cache_connection: /tmp/ansible_inventory_cache
cache_timeout: 300
"""


def discover_accounts(hub_profile: str) -> list[dict]:
    """Returns every ACTIVE account in the Organization except the
    management account itself (the management account isn't expected to
    run monitored workloads directly -- adjust the filter if it does)."""
    session = boto3.Session(profile_name=hub_profile)
    org = session.client("organizations")

    management_account_id = org.describe_organization()["Organization"]["MasterAccountId"]

    accounts = []
    paginator = org.get_paginator("list_accounts")
    for page in paginator.paginate():
        for acct in page["Accounts"]:
            if acct["Status"] != "ACTIVE":
                continue
            if acct["Id"] == management_account_id:
                continue
            accounts.append({"id": acct["Id"], "name": acct["Name"]})
    return accounts


def write_cli_profile(hub_profile: str, account_id: str, region: str) -> str:
    """Adds/updates a role-assuming profile in ~/.aws/config. boto3/awscli
    transparently assume AnsibleSpokeRole and refresh the STS session as it
    expires -- no long-lived per-account credentials are ever stored."""
    profile_name = f"acct-{account_id}"
    config_path = Path(os.environ.get("AWS_CONFIG_FILE", Path.home() / ".aws" / "config"))
    config_path.parent.mkdir(parents=True, exist_ok=True)

    config = configparser.ConfigParser()
    if config_path.exists():
        config.read(config_path)

    section = f"profile {profile_name}"
    if section not in config:
        config[section] = {}
    config[section]["role_arn"] = f"arn:aws:iam::{account_id}:role/{SPOKE_ROLE_NAME}"
    config[section]["source_profile"] = hub_profile
    config[section]["region"] = region
    config[section]["role_session_name"] = "ansible-disk-monitor"

    with open(config_path, "w") as f:
        config.write(f)

    return profile_name


def write_inventory_file(account: dict, profile_name: str, regions: list[str], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    content = INVENTORY_TEMPLATE.format(
        profile_name=profile_name,
        region_lines="\n".join(f"  - {r}" for r in regions),
        account_id=account["id"],
        account_name=account["name"],
        primary_region=regions[0],
    )
    (out_dir / f"{account['id']}.aws_ec2.yml").write_text(content)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hub-profile", required=True, help="AWS CLI profile for the automation/hub account")
    parser.add_argument("--region", action="append", dest="regions", default=None, help="Region to scan (repeatable)")
    parser.add_argument(
        "--inventory-dir",
        default=str(Path(__file__).resolve().parent.parent / "inventory" / "accounts"),
        help="Where to write the generated per-account inventory files",
    )
    args = parser.parse_args()
    regions = args.regions or ["us-east-1", "us-west-2"]

    accounts = discover_accounts(args.hub_profile)
    print(f"Discovered {len(accounts)} active member account(s) in the Organization.")

    out_dir = Path(args.inventory_dir)
    for account in accounts:
        profile_name = write_cli_profile(args.hub_profile, account["id"], regions[0])
        write_inventory_file(account, profile_name, regions, out_dir)
        print(f"  {account['id']} ({account['name']}) -> {out_dir / (account['id'] + '.aws_ec2.yml')}")

    print(f"\nDone. Run playbooks against the whole fleet with:\n  ansible-playbook -i {out_dir} playbooks/monitor_disk.yml")


if __name__ == "__main__":
    main()
